theme: null
plugins:
  - jekyll-commonmark-ghpages
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-seo-tag
google_analytics: 'UA-38690663-1'
permalink: "/:title:output_ext"
title: &title "Carson Reinke's (🚗☀☔🔑) Blog"
description: *title
url: "https://reinke.co"